# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('credits', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gpacalc.Class')),
                ('collegename', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gpacalc.College')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(choices=[(4.0, 'A'), (3.0, 'B'), (2.0, 'C'), (1.0, 'D'), (0.0, 'F')], decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer')], max_length=2)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gpa', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JU', 'Junior'), ('SE', 'Senior+')], max_length=2)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('season', 'year')]),
        ),
        migrations.AddField(
            model_name='collegeorganizer',
            name='grade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gpacalc.Grade'),
        ),
        migrations.AddField(
            model_name='collegeorganizer',
            name='semestername',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gpacalc.Semester'),
        ),
        migrations.AddField(
            model_name='collegeorganizer',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gpacalc.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='collegeorganizer',
            unique_together=set([('username', 'collegename', 'semestername', 'classname')]),
        ),
    ]
